export enum PurchaseStatus {
  CADASTRADO = 'CADASTRADO',
  EM_TRANSITO_JP = 'EM_TRANSITO_JP',
  RECEBIDO_NO_JAPAO = 'RECEBIDO_NO_JAPAO',
  EM_INSPECAO = 'EM_INSPECAO',
  AGUARDANDO_CONSOLIDACAO = 'AGUARDANDO_CONSOLIDACAO',
  CONSOLIDADO = 'CONSOLIDADO',
  CANCELADO = 'CANCELADO',
}
